#Sprites

#Scrape sprites from Pokemon DB along with shinies
- Figure out what to do with Pokemon with different formes
```{r}
h2 <- read_html("https://pokemondb.net/pokedex/shiny")

norm_shiny_sprites <- h2 %>% 
  html_nodes("span.infocard-lg-img") %>% 
  html_nodes("span") %>% 
  html_attr("data-src")

appearance <- norm_shiny_sprites %>% 
  gsub("(https://img.pokemondb.net/sprites/home/)(.*)/(.*).png$","\\2",.)

name <- norm_shiny_sprites %>% 
  gsub("(https://img.pokemondb.net/sprites/home/)(.*)/(.*).png$","\\3",.) %>% 
  gsub("-"," ",.) %>% str_to_title()

#Edge cases
name <- name %>% 
  gsub("(Mr)","\\1.",.) %>%
  gsub("(Jr)","\\1.",.) %>% 
  gsub("(Ho Oh)","Ho-Oh",.) %>% 
  gsub("(Far|Sir)fetchd","\\1fetch'd",.) %>% 
  gsub("Nidoran F","Nidoran♀",.) %>% 
  gsub("Nidoran M","Nidoran♂",.) %>% 
  gsub("Porygon Z","Porygon-Z",.) %>% 
  gsub("(Kommo|Jangmo|Hakamo).(O)","\\1-o",.) %>% 
  gsub("(Type) ","\\1: ",.)

NS_sprites <- tibble(Name = name, Class = appearance, Url = norm_shiny_sprites)
```

#Fix edge cases
```{r}
temp <- allMons %>% filter(Gen < 8, Name != 'MissingNo.')

test <- left_join(temp, NS_sprites, by = "Name")
test[which(is.na(test$Url)),]$Name
(Nas <- sum(is.na(test$Url)))

#pattern
pattern = "Ind"

allMons$Name %>% str_subset(pattern)
name %>% str_subset(pattern)


```

#Different Formes
 - What information do I need for each forme?
```{r}
(info1 <- names(allMons))
#Learnset
#Level, Move, Type, Cat., Pwr., Acc., PP, Method
```